    $(document).ready(function()
      {
        $("button.back").click(function()
          {
            window.location.href='../admin/adminpanel.php';
          }
          );
      }
      );
